default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { db } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { poostgres } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { '' } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: railsgql_development

test:
  <<: *default
  database: railsgql_test
production:
  <<: *default
  database: railsgql_production
